language: c
matrix:
  include:
  - env: BUILD_TYPE=coverage
    install:
      - gem install coveralls-lcov
    after_success:
      - coveralls-lcov build/coverage_test.info
      - bash <(curl -s https://codecov.io/bash)
  - env: BUILD_TYPE=lxc CMAKE_ARGS="-DBPWS_BUILD_CHECK=ON" LXC_DIST=trusty LXC_ARCH=i386
  - env: BUILD_TYPE=lxc CMAKE_ARGS="-DBPWS_BUILD_CHECK=ON" LXC_DIST=trusty LXC_ARCH=amd64
script:
  - ./travis_build.sh $BUILD_TYPE $CMAKE_ARGS $LXC_DIST $LXC_ARCH
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - check
    - cmake
    - lcov
    - libssl-dev
    - libjson-c-dev
