environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017
      OPENSSL_VERSION: Win32OpenSSL-1_0_2L
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017 Win64
      OPENSSL_VERSION: Win64OpenSSL-1_0_2L

platform: x64

install:
  - ps: Start-FileDownload 'http://slproweb.com/download/${Env:OPENSSL_VERSION}.exe'
  - ps: Start-Process "${Env:OPENSSL_VERSION}.exe" -ArgumentList "/silent /verysilent /sp- /suppressmsgboxes" -Wait
  
build_script:
  - md build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DBPWS_BUILD_CHECK=ON -DBPWS_BUILD_LIBWEBSOCKETS=ON -G "%GENERATOR%"
  - cmake --build . --config Release

test_script:
  - cmake --build . --config Release --target RUN_TESTS
