environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017 Win64

platform: x64

build_script:
  - md build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DBPWS_BUILD_CHECK=ON -DBPWS_BUILD_LIBWEBSOCKETS=ON -G "%GENERATOR%"
  - cmake --build . --config Release

test_script:
  - cmake --build . --config Release --target RUN_TESTS
